version: "3.5"
services:
  dev-db:
    image: mysql:8.0.30
    container_name: "mysql_dev_db"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nestjs_starter
    networks:
      - default

  test-db:
    image: mysql:8.0.30
    container_name: "mysql_test_db"
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nestjs_starter
    networks:
      - default


